### ISSUE TITLE
Multilingual Version

### ISSUE THREAD

**Issue by fugazi73** [motopress/mphb_app#10]
Hello Motopress Team,

I would like to propose a multilingual version such as German, I would also do the translation.
Reason: I couldn't offer my customers' version because they don't speak English.
I look forward to watching the development and thank you for starting the development.

Best Regards
Patrick

**Comment by mototeam** [comment]
Internalization feature implemented in version 1.2.0 (Jul 13 2023)
You can add or edit translations here https://crowdin.com/project/mphb-app
Write us at motopressapp[@]gmail.com if you need other languages.
