### ISSUE TITLE
Wrong status on abandoned bookings

### ISSUE THREAD

**Issue by Paul181516** [motopress/mphb_app#16]
I dont know why but all the bookings with cancelled or unfinished payments have "Admin Required" status on the bookings tabs. What can i do to fix this? I cant be checking this manually with multiple bookings per day. The status should be "Abandoned" and this should be automatic.
Im using Woocommerce.

Please help me.
Thanks
![Screenshot 2024-04-19 at 10-50-00 Editar reserva Vuriloche — WordPress](https://github.com/motopress/mphb_app/assets/66581295/d8848fb9-67ce-4979-ad35-e31f355e02b4)
![Screenshot 2024-04-19 at 10-49-54 Editar reserva Vuriloche — WordPress](https://github.com/motopress/mphb_app/assets/66581295/4ab3f873-5c51-4ef6-8164-59a650844704)

**Comment by mototeam** [comment]
It appears the problem originates from outside the mobile application. We recommend [contacting support](https://support.motopress.com/hc/en-us/requests/new) for further assistance.
