### ISSUE TITLE
Cannot access reservations from calendar - iOS

### ISSUE THREAD

**Issue by finner** [motopress/mphb_app#18]
When using the iOS app and trying to retrieve a reservation from the calendar I almost get immediately the following error: type 'Null' is not a subtype of type 'int' in type cast.
Using latest hotel booking plugin and latest iOS app.

**Comment by mototeam** [comment]
Your issue requires further investigation. Please [contact support](https://support.motopress.com/hc/en-us/requests/new) if it is still available.
